# Generated by Django 6.0.6 on 2026-07-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ogloszenie',
            options={'verbose_name': 'Ogłoszenie', 'verbose_name_plural': 'Ogłoszenia'},
        ),
    ]
