# Generated by Django 6.0.6 on 2026-07-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0004_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
    ]
